import Head from 'next/head';
import Footer from '../../../Components/Footer/Footer';
import Navbar from '../../../Components/Navbar/Navbar';
import Offers from '../../../Components/Offers/Offers';
import TopText from '../../../Components/TopText/TopText';
import styles from '../../styles/about.module.scss';

const index = () => (
    <div className={styles.about_page}>
        <Head>
            <title>About Us</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <TopText />
        <Navbar />
        <div className={styles.about_page_header}>
            <div className={styles.bd_header_img} />
        </div>

        <div className={styles.about_page_text}>
            <h1>About Us</h1>

            <p>
                At Lucianaschiles, we offer a wide range of spices including chili powders, spice
                blends, and whole spices, all carefully sourced and selected for their quality and
                authenticity. We are committed to supporting small-scale farmers and producers who
                use sustainable and ethical farming practices.
            </p>
        </div>
        <div className={styles.about_page_main}>
            <Offers />
        </div>
        <Footer />
    </div>
);

export default index;
