/* eslint-disable jsx-a11y/no-static-element-interactions */
/* eslint-disable react-hooks/rules-of-hooks */
import Head from 'next/head';
import Image from 'next/image';
import { useState } from 'react';
import { FaAngleLeft, FaAngleRight, FaTimes } from 'react-icons/fa';
import Footer from '../../../Components/Footer/Footer';
import Navbar from '../../../Components/Navbar/Navbar';
import img1 from '../../../images/bg1.jpg';
import img10 from '../../../images/bg10.jpg';
import img11 from '../../../images/bg11.jpg';
import img2 from '../../../images/bg2.jpg';
import img3 from '../../../images/bg3.jpg';
import img4 from '../../../images/bg4.jpg';
import img5 from '../../../images/bg5.jpg';
import img6 from '../../../images/bg6.jpg';
import img7 from '../../../images/bg7.jpg';
import img8 from '../../../images/bg8.jpg';
import img9 from '../../../images/bg9.jpg';
import styles from '../../styles/media.module.scss';

const spices = [
    {
        id: 1,
        name: 'Cumin',
        image: img1,
    },
    {
        id: 2,
        name: 'Coriander',
        image: img2,
    },
    {
        id: 3,
        name: 'Turmeric',
        image: img3,
    },
    {
        id: 4,
        name: 'Ginger',
        image: img4,
    },
    {
        id: 5,
        name: 'Ginger',
        image: img5,
    },
    {
        id: 6,
        name: 'Ginger',
        image: img6,
    },
    {
        id: 7,
        name: 'Ginger',
        image: img7,
    },
    {
        id: 8,
        name: 'Ginger',
        image: img8,
    },
    {
        id: 9,
        name: 'Ginger',
        image: img9,
    },
    {
        id: 10,
        name: 'Ginger',
        image: img10,
    },
    {
        id: 11,
        name: 'Ginger',
        image: img11,
    },
    {
        id: 12,
        name: 'Ginger',
        image: img3,
    },
];

const index = () => {
    const [selectedSpice, setSelectedSpice] = useState(null);

    const handleSpiceClick = (spice) => {
        setSelectedSpice(spice);
    };

    const handleNextClick = () => {
        const currentIndex = spices.findIndex((spice) => spice.id === selectedSpice.id);
        const nextIndex = currentIndex + 1;
        if (nextIndex === spices.length) {
            setSelectedSpice(spices[0]);
        } else {
            setSelectedSpice(spices[nextIndex]);
        }
    };

    const handlePrevClick = () => {
        const currentIndex = spices.findIndex((spice) => spice.id === selectedSpice.id);
        const prevIndex = currentIndex - 1;
        if (prevIndex < 0) {
            setSelectedSpice(spices[spices.length - 1]);
        } else {
            setSelectedSpice(spices[prevIndex]);
        }
    };

    const handleClose = () => {
        setSelectedSpice(null);
    };

    return (
        <div className={styles.media_page}>
            <Head>
                <title>Media</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <div className={styles.media_page_main}>
                <div className={styles.image_row}>
                    {spices.map((spice) => (
                        <div key={spice.id} className={styles.col_md_3}>
                            <Image
                                src={spice.image}
                                alt={spice.name}
                                onClick={() => handleSpiceClick(spice)}
                                width={270}
                                height={200}
                                className={styles.image}
                            />
                        </div>
                    ))}
                </div>
                {selectedSpice && (
                    <div className={styles.slider_wrapper}>
                        <button
                            onClick={handlePrevClick}
                            type="button"
                            className={styles.prev_button}
                        >
                            <FaAngleLeft />
                        </button>
                        <div className={styles.slider}>
                            <Image
                                src={selectedSpice.image}
                                alt={selectedSpice.name}
                                width={500}
                                height={400}
                                className={styles.slide_image}
                                objectFit="cover"
                                layout="responsive"
                            />
                        </div>
                        <button
                            onClick={handleNextClick}
                            type="button"
                            className={styles.next_button}
                        >
                            <FaAngleRight />
                        </button>

                        <span onClick={handleClose}>
                            <FaTimes />
                        </span>
                    </div>
                )}
            </div>
            <Footer />
        </div>
    );
};

export default index;
