import Head from 'next/head'
import Blog from '../../../Components/Blog/Blog'
import Footer from '../../../Components/Footer/Footer'
import Navbar from '../../../Components/Navbar/Navbar'
import styles from '../../styles/blogs.module.scss'

const index = ({blogs}) => {
  return (
    <div className={styles.blog_page}>
      <Head>
            <title>Blogs</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navbar />
            <div className={styles.blog_page_main}>
            {blogs.map((blog) => {
                return <Blog key={blog._id} blog={blog} />
            })}
            </div>
        <Footer />
    </div>
  )
}

export default index

// fetch all the necessary items
export async function getStaticProps() {
    const res = await fetch('https://lucianaschiles-backend.onrender.com/api/blogs/all')

    const data = await res.json();

    const blogs = data.message;
    return {
      props: {
        blogs: blogs || null,
      },
    }
};