/* eslint-disable jsx-a11y/iframe-has-title */
/* eslint-disable react-hooks/rules-of-hooks */
import emailjs from '@emailjs/browser';
import Head from 'next/head';
import { useRef, useState } from 'react';
import Swal from 'sweetalert2';
import Footer from '../../../Components/Footer/Footer';
import Navbar from '../../../Components/Navbar/Navbar';
import TopText from '../../../Components/TopText/TopText';
import styles from '../../styles/contact.module.scss';

const index = () => {
    const [name, setName] = useState('');
    const [email, setEmail] = useState('');
    const [message, setMessage] = useState('');
    const form = useRef();
    const Toast = Swal.mixin({
        toast: true,
        position: 'bottom-end',
        showConfirmButton: false,
        timer: 3000,
        timerProgressBar: true,
        width: '250px',
        padding: '.25rem',
        didOpen: (toast) => {
            toast.addEventListener('mouseenter', Swal.stopTimer);
            toast.addEventListener('mouseleave', Swal.resumeTimer);
        },
    });

    const handleSubmit = (e) => {
        e.preventDefault();
        try {
            emailjs
                .sendForm('service_oa2im2q', 'template_l5cjev4', form.current, 'mqlVmI9Fm3eB-SSCf')
                .then(
                    (result) => {
                        console.log(result.text);
                    },
                    (error) => {
                        console.log(error.text);
                    }
                );

            Toast.fire({
                icon: 'success',
                title: 'Successfully sent.',
            });

            setName('');
            setEmail('');
            setMessage('');
        } catch (error) {
            console.log(error);
        }
    };

    return (
        <div className={styles.contact_page}>
            <Head>
                <title>Contact Us</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <TopText />
            <Navbar />
            <div className={styles.contact_page_main}>
                <div className={styles.contact_page_location}>
                    <h2>CONTACT INFO</h2>
                    <p>5811 HUDSON AVE, WEST NEW YORK</p>
                    <p>NJ, 07093, UNITED STATES</p>

                    <p className={styles.contact_phn}>Phone:</p>
                    <span>+0000000000</span>
                </div>

                <div className={styles.contact_page_form}>
                    <h2>GET IN TOUCH</h2>
                    <form ref={form} onSubmit={handleSubmit} className={styles.contact_form}>
                        <div className={styles.form_top_inp}>
                            <input
                                type="text"
                                name="user_name"
                                placeholder="Name"
                                value={name}
                                onChange={(e) => setName(e.target.value)}
                                required
                            />

                            <input
                                type="email"
                                name="user_email"
                                placeholder="Email Address"
                                value={email}
                                onChange={(e) => setEmail(e.target.value)}
                                required
                            />
                        </div>

                        <textarea
                            placeholder="Leave Your Message.."
                            cols="40"
                            rows="10"
                            name="message"
                            value={message}
                            required
                            onChange={(e) => setMessage(e.target.value)}
                        />

                        <input type="submit" value="SUBMIT" />
                    </form>
                </div>
            </div>

            <iframe
                src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d12083.732122906242!2d-74.01700316386395!3d40.78548641614695!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89c258131938b8d5%3A0xe39c30a8afef2d96!2sWest%20New%20York%2C%20NJ%2007093%2C%20USA!5e0!3m2!1sen!2sbd!4v1679951267434!5m2!1sen!2sbd"
                width="1600"
                height="600"
                style={{ border: '0' }}
                allowfullscreen=""
                loading="lazy"
                referrerPolicy="no-referrer-when-downgrade"
            />
            <Footer />
        </div>
    );
};

export default index;
